objects/Consultant__c.object
<CustomObject>
    <fields>
        <fullName>User_Name__c</fullName>
        <formula>User_Profile__r.FirstName + &apos; &apos; + User_Profile__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User Name</label>
        <type>Text</type>
    </fields>
    <label>Consultant</label>
    <nameField>
        <label>Consultant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consultants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <description>Related to opportunity, tracks summary info such as estimated, quoted and actual durations.</description>
    <fields>
        <fullName>Account_ID__c</fullName>
        <formula>Opportunity_Name__r.AccountId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <formula>Customer_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the customer name</inlineHelpText>
        <label>Customer Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_Effort_Hrs__c</fullName>
        <label>Estimated Effort (Hrs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Opportunity</inlineHelpText>
        <label>Opportunity Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Customer_Name__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Stage__c</fullName>
        <formula>TEXT(Opportunity_Name__r.StageName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Carried_Over_Hrs__c</fullName>
        <label>Time Carried Over (Hrs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Timesheet__c.object
<CustomObject>
    <description>Tracks project status info</description>
    <fields>
        <fullName>Billable__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Deselect if work will not be billed to the client.</inlineHelpText>
        <label>Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Consultant_Name__c</fullName>
        <label>Consultant/Trainer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant</label>
        <referenceTo>Consultant__c</referenceTo>
        <relationshipLabel>Project Timesheets</relationshipLabel>
        <relationshipName>Project_Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <formula>Customer__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Timesheets</relationshipLabel>
        <relationshipName>Project_Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Work__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date of Work</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <picklist>
            <picklistValues>
                <fullName>Presales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultancy - Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultancy - Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Import</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prep</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration (Hours)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>P_Opportunity_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Timesheets</relationshipLabel>
        <relationshipName>Project_Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name_Text__c</fullName>
        <formula>P_Opportunity_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Name (Text)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Opportunity Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must pick a project related to the customer</errorMessage>
            <filterItems>
                <field>Opportunity.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Project Timesheets</relationshipLabel>
        <relationshipName>Project_Timesheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Stage__c</fullName>
        <label>Project Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Kick-Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analysis &amp; Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Mangement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Timesheet</label>
    <nameField>
        <displayFormat>{DD}{MM}{YYYY}-{0}</displayFormat>
        <label>Project Timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ProjectTimesheetFormController.cls
public class ProjectTimesheetFormController {

    @AuraEnabled
    public static Project_Timesheet__c getProjectTimesheet(String recordId) {
		System.debug('recordId: ' + recordId);
        if((recordId == '') || (recordId == null)) {            
			Consultant__c c = [SELECT Id,Name,User_Name__c FROM Consultant__c WHERE User_Name__c = :userinfo.getName()];            
            return new Project_Timesheet__c(
	            Consultant__c = c.Id
            );
        } else {
            return [SELECT Id,Name,Date_of_Work__c,Project_Name__c,
                    Project_Name_Text__c,P_Opportunity_Name__c,
                    Billable__c,Consultant_Name__c,Consultant__c,Customer__c,
                    Customer_Name__c,Duration__c,Project_Stage__c,
                    Notes__c,Description__c, Date_of_Work_Text__c 
                    FROM Project_Timesheet__c
                    WHERE Id = :recordId][0];            
        }
    } 
    
    @AuraEnabled
    public static Project_Timesheet__c saveProjectTimesheet(Project_Timesheet__c pt) {
        System.debug('saving');
        System.debug(pt.P_Opportunity_Name__c);
        if(pt.Project_Name__c == null) {
            System.debug('Need to get the Opportunity from the Project');
            Project__c proj = [SELECT Customer_Name__c, Opportunity_Name__c FROM Project__c WHERE ID = :pt.P_Opportunity_Name__c];
            pt.Project_Name__c = proj.Opportunity_Name__c;
            pt.Customer__c = proj.Customer_Name__c;
        }
        if(pt.Consultant_Name__c == null) {
	        Consultant__c c = [SELECT Id,Name,User_Name__c FROM Consultant__c WHERE id = :pt.Consultant__c];
            pt.Consultant_Name__c = c.User_Name__c;
        }
        upsert pt;
        return pt;
    }


    @AuraEnabled
    public static Project_Timesheet__c cloneProjectTimesheet(Project_Timesheet__c pt) {
        System.debug('cloning');
        System.debug(pt.P_Opportunity_Name__c);
        if(pt.Project_Name__c == null) {
            System.debug('Need to get the Opportunity from the Project');
            Project__c proj = [SELECT Customer_Name__c, Opportunity_Name__c FROM Project__c WHERE ID = :pt.P_Opportunity_Name__c];
            pt.Project_Name__c = proj.Opportunity_Name__c;
            pt.Customer__c = proj.Customer_Name__c;
        }
        if(pt.Consultant_Name__c == null) {
	        Consultant__c c = [SELECT Id,Name,User_Name__c FROM Consultant__c WHERE id = :pt.Consultant__c];
            pt.Consultant_Name__c = c.User_Name__c;
        }
		Project_Timesheet__c pt_c = pt.clone(false, true);
        insert pt_c;
        return pt_c;
    }
    
    @AuraEnabled
    public static void deleteProjectTimesheet(ID recordId) {
        Project_Timesheet__c pt = new Project_Timesheet__c(id= recordId);
		delete pt;        
    }    
    
    @AuraEnabled
    public static List<Consultant__c> getConsultants() {
        return [SELECT Id,Name,User_Name__c FROM Consultant__c];
    } 
    
    
    @AuraEnabled
    public static List<Project__c> getProjects() {
        return [SELECT Id,Name,CreatedDate,Opportunity_Name__c,Customer_Name__c,
                		Account_ID__c,Opportunity_Stage__c,Client_Name__c,
                		Time_Carried_Over_Hrs__c,Estimated_Effort_Hrs__c 
                FROM Project__c
               	WHERE Opportunity_Stage__c = 'Closed Won'
                ORDER BY CreatedDate DESC, NAME ASC
               ];        
    } 
    
    
    @AuraEnabled
    public static List<String> getDescriptionOptions() {    
    	// this function builds the list of SelectOptions for the Department field   
        List<String> options = new List<String>();
        // do describe here to get the Department__c field picklist values
        Schema.DescribeFieldResult deptDFR = Schema.sObjectType.Project_Timesheet__c.fields.Description__c;
        for (Schema.PickListEntry deptPickVal : deptDFR.getPicklistValues()){
        	// create a selectoption for each pickval
        	options.add(deptPickVal.getLabel());
        }
        return options;
    }

    @AuraEnabled
    public static List<String> getProjectStages() {    
    	// this function builds the list of SelectOptions for the Department field   
        List<String> options = new List<String>();
        // do describe here to get the Department__c field picklist values
        Schema.DescribeFieldResult deptDFR = Schema.sObjectType.Project_Timesheet__c.fields.Project_Stage__c;
        for (Schema.PickListEntry deptPickVal : deptDFR.getPicklistValues()){
        	// create a selectoption for each pickval
        	options.add(deptPickVal.getLabel());
        }
        return options;
    }
    
}