objects/Project_Timesheet__c.object
<CustomObject>
    <description>Tracks project status info</description>
    <fields>
        <fullName>Billable__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Deselect if work will not be billed to the client.</inlineHelpText>
        <label>Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Consultant_Name__c</fullName>
        <label>Consultant/Trainer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <formula>Customer__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Timesheets</relationshipLabel>
        <relationshipName>Project_Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Work__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date of Work</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <picklist>
            <picklistValues>
                <fullName>Presales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultancy - Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultancy - Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Import</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prep</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration (Hours)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>P_Opportunity_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Timesheets</relationshipLabel>
        <relationshipName>Project_Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name_Text__c</fullName>
        <formula>P_Opportunity_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Name (Text)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Opportunity Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must pick a project related to the customer</errorMessage>
            <filterItems>
                <field>Opportunity.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Project Timesheets</relationshipLabel>
        <relationshipName>Project_Timesheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Stage__c</fullName>
        <label>Project Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Kick-Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analysis &amp; Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Mangement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Timesheet</label>
    <nameField>
        <displayFormat>{DD}{MM}{YYYY}-{0}</displayFormat>
        <label>Project Timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ProjectTimesheetsHandler.cls
public class ProjectTimesheetsHandler {

    @AuraEnabled
    public static List<Project_Timesheet__c> getMyTimesheets_OLD() {        
        List<Project_Timesheet__c> projectsTimesheet = [SELECT Id,Name,Date_of_Work__c,Project_Name__c,
                                                        Project_Name_Text__c,P_Opportunity_Name__c,
                                                        Billable__c,Consultant_Name__c,Customer__c,
                                                        Customer_Name__c,Duration__c,Project_Stage__c,
                                                        Notes__c,Description__c, Date_of_Work_Text__c 
                                                        FROM Project_Timesheet__c
                                                        WHERE Consultant_Name__c = :userinfo.getName()
                                                       ORDER BY Date_of_Work__c DESC, Customer_Name__c ASC
                                                       LIMIT 5];

        return projectsTimesheet;
    }

    @AuraEnabled
    public static ProjectTimesheetPagedResult getMyTimesheets(String searchKey, Decimal pageNumber) {        
        System.debug('searchKey: ' + searchKey);
        System.debug('pageNumber: ' + pageNumber);
		Integer pageSize = 8;
        System.debug('pageSize: ' + pageSize);
        String key = '%' + searchKey + '%';
        Integer offset = ((Integer)pageNumber - 1) * pageSize;
        System.debug('pageSize: ' + pageSize);
        
        ProjectTimesheetPagedResult p =  new ProjectTimesheetPagedResult();
        p.pageSize = pageSize;
        p.page = (Integer) pageNumber;
        p.total = [SELECT count() FROM Project_Timesheet__c
					WHERE Consultant_Name__c = :userinfo.getName()];
        p.projectTimesheets = [SELECT Id,Name,Date_of_Work__c,Project_Name__c,
									Project_Name_Text__c,P_Opportunity_Name__c,
                                    Billable__c,Consultant_Name__c,Customer__c,
                                    Customer_Name__c,Duration__c,Project_Stage__c,
                                    Notes__c,Description__c, Date_of_Work_Text__c 
                               FROM Project_Timesheet__c
                               WHERE Consultant_Name__c = :userinfo.getName()
		                       AND (Customer_Name__c LIKE :key OR Project_Name_Text__c LIKE :key)
                               ORDER BY Date_of_Work__c DESC, Customer_Name__c ASC
                               LIMIT 8 OFFSET :offset];
        System.debug(p);
        return p;        
    }
    
}